"""
Corvus report generator.
Uses onboarding watch_signals to route findings to the right teams.
"""

from datetime import datetime
import os

class DebriefGenerator:

    def __init__(self, config: dict, onboarding: dict):
        self.config = config
        self.onboarding = onboarding
        self.company = onboarding.get("company", "Your Company")
        self.site = onboarding.get("site", "Plant")
        self.teams = onboarding.get("teams", [])
        self.terminology = onboarding.get("terminology", {})
        self.output_dir = config.get("reporting", {}).get("output_dir", "./reports") 

    def generate(self, debrief_text: str) -> str:
        now = datetime.now()
        date_str = now.strftime("%Y-%m-%d")
        time_str = now.strftime("%H:%M")

        lines = []

        # --- header ---
        lines.append("=" * 60)
        lines.append("🦅  CORVUS DEBRIEF REPORT")
        lines.append(f"    {self.company} — {self.site}")
        lines.append(f"    {date_str} | {time_str}")
        lines.append("=" * 60)
        lines.append("")

        # --- intelligence summary ---
        lines.append("INTELLIGENCE SUMMARY")
        lines.append("-" * 60)
        lines.append(debrief_text.strip())
        lines.append("")

        # --- team sections ---
        lines.append("=" * 60)
        lines.append("MEETING CHECKLISTS BY TEAM")
        lines.append("=" * 60)
        lines.append("")

        for team in self.teams:
            lines.append(f"📋  {team['name'].upper()}")
            lines.append(f"    {team.get('meeting', 'Standing Meeting')}")

            # alert recipients
            recipients = team.get("alert_recipients", [])
            if recipients:
                roles = ", ".join(r["role"] for r in recipients)
                lines.append(f"    Notify: {roles}")

            lines.append("")
            lines.append("    Focus areas:")
            for item in team.get("cares_about", []):
                lines.append(f"      · {item}")

            lines.append("")
            lines.append("    Action items from this debrief:")
            actions = self._extract_actions_for_team(debrief_text, team)
            lines.append(actions)
            lines.append("")
            lines.append("-" * 60)
            lines.append("")

        lines.append("Generated by Corvus Debrief 🦅")
        lines.append("")

        return "\n".join(lines)

    def _extract_actions_for_team(self, debrief_text: str, team: dict) -> str:
        """
        Match debrief lines against team's cares_about keywords.
        """
        team_name = team["name"].lower()
        keywords = [k.lower() for k in team.get("cares_about", [])]
        keywords.append(team_name)

        # also match watch_signals terminology
        watch_signals = team.get("watch_signals", [])
        signal_terms = {
            "stalled_build": ["blocked", "stalled", "waiting"],
            "paused_build": ["paused", "break"],
            "delayed_build": ["delayed", "at risk", "missed", "overtime"],
            "unassigned_operator": ["unassigned", "unstaffed", "no operator"]
        }
        for signal in watch_signals:
            keywords.extend(signal_terms.get(signal, []))

        relevant_lines = []
        for line in debrief_text.splitlines():
            line_lower = line.lower()
            if any(kw in line_lower for kw in keywords):
                if any(marker in line for marker in
                       ["-", "→", "🔴", "🟡", "🔵", "⚪"]):
                    relevant_lines.append(line.strip())

        if relevant_lines:
            return "\n".join(
                f"      - {l.lstrip('- ')}" for l in relevant_lines
            )
        return "      - No direct action items this cycle. Monitor for changes."

    def output(self, report: str):
        """Print to console."""
        print(report)
        ##Markdown file
        os.makedirs(self.output_dir, exist_ok=True)
        date_str = datetime.now().strftime("%Y-%m-%d_%H-%M")
        filename = f"corvus_debrief_{date_str}.md"
        filepath = os.path.join(self.output_dir, filename)

        with open(filepath, "w") as f:
            f.write(report)

        print(f"\n[CORVUS] Report saved → {filepath}")
